"""Per-finding provenance file generator.

Each call writes (or skips, idempotently) `provenance/finding-N.md`, a
journalist-readable reference showing where a finding's numbers came
from, the per-month source URLs, the FX rates applied, what each
caveat means in plain English, and any cross-source corroboration. The
file is a frozen snapshot taken at generation time — if the underlying
finding is later superseded, that older provenance file is left
in place and a fresh file is generated for the new finding id.

Two entry points:

- `generate_for_finding(finding_id)` — the canonical generator.
  Idempotent: skips if `provenance/finding-N.md` already exists. Pass
  `force=True` to regenerate (e.g. after a methodology refresh).
- The briefing-pack export() flow calls this for every finding id cited
  in the rendered brief / leads doc, then copies the generated files
  into the export bundle's `provenance/` subdir so a journalist
  forwarded only the bundle has everything they need.

CLI: `python scrape.py --finding-provenance 57378`.

Generator coverage as of 2026-05-14:
- gacc_bilateral_aggregate_yoy[_import] — full template
- Everything else — stub file noting "detailed generator pending"

Extend by adding a per-subkind renderer to `_RENDERERS`.
"""

from __future__ import annotations

import logging
import os
from datetime import date, datetime, timezone
from pathlib import Path

import psycopg2
import psycopg2.extras

import lookups

log = logging.getLogger(__name__)


PROVENANCE_DIR = Path(os.environ.get("GACC_PROVENANCE_DIR", "provenance"))


def _conn():
    return psycopg2.connect(os.environ["DATABASE_URL"])


def _provenance_path(finding_id: int) -> Path:
    return PROVENANCE_DIR / f"finding-{finding_id}.md"


def generate_for_finding(
    finding_id: int, force: bool = False, supported_only: bool = False,
) -> Path | None:
    """Generate `provenance/finding-N.md` if absent. Returns the path either way.

    `force=True` regenerates an existing file — useful after a methodology
    refresh or to pick up a supersede that landed after the file was first
    written. Default is to leave existing files alone so a journalist
    re-reading an earlier export sees what they read.

    `supported_only=True` returns None (and skips writing) when the
    finding's subkind doesn't yet have a dedicated renderer. The
    bundle-into-export flow passes this to avoid littering the export
    folder with stub files for the ~thousands of findings whose
    subkinds aren't covered yet. The CLI path leaves this False so a
    journalist asking about any finding gets at least the stub."""
    with _conn() as conn, conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
        cur.execute(
            """
            SELECT id, kind, subkind, title, body, detail, observation_ids,
                   created_at, last_confirmed_at,
                   superseded_at, superseded_by_finding_id
              FROM findings WHERE id = %s
            """,
            (finding_id,),
        )
        finding = cur.fetchone()
    if finding is None:
        raise ValueError(
            f"No finding with id={finding_id}. Cannot generate provenance."
        )

    if supported_only and finding["subkind"] not in _RENDERERS:
        return None

    dest = _provenance_path(finding_id)
    if dest.exists() and not force:
        log.debug("provenance %s already exists; skipping", dest)
        return dest

    renderer = _RENDERERS.get(finding["subkind"], _render_stub)
    body = renderer(finding)

    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(body)
    log.info("provenance: wrote %s", dest)
    return dest


# ---------------------------------------------------------------------------
# Renderers, one per subkind
# ---------------------------------------------------------------------------


def _generated_banner(finding_id: int) -> str:
    return (
        f"*Auto-generated by `python scrape.py --finding-provenance "
        f"{finding_id}` on {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%MZ')}. "
        f"This file is a frozen snapshot of the finding at generation time; "
        f"if the finding is later superseded, a fresh provenance file is "
        f"generated for the new finding id and this one is left in place.*\n"
    )


def _supersede_status(finding: dict) -> str:
    if finding["superseded_at"] is None:
        return f"**Status**: active. Last confirmed {finding['last_confirmed_at']:%Y-%m-%d %H:%M %Z}."
    return (
        f"**Status**: superseded {finding['superseded_at']:%Y-%m-%d} → "
        f"`finding/{finding['superseded_by_finding_id']}`. Provenance below "
        f"reflects this finding's data at the time it was published."
    )


def _fmt_eur(n: float) -> str:
    if abs(n) >= 1e9:
        return f"€{n/1e9:.2f}B"
    if abs(n) >= 1e6:
        return f"€{n/1e6:.1f}M"
    return f"€{n:,.0f}"


def _fmt_pct(p: float) -> str:
    return f"{p*100:+.2f}%"


def _render_gacc_bilateral_aggregate_yoy(finding: dict) -> str:
    """Bilateral-aggregate generator. Covers both export and import flows
    (subkinds `gacc_bilateral_aggregate_yoy` and
    `gacc_bilateral_aggregate_yoy_import`)."""
    detail = finding["detail"]
    totals = detail["totals"]
    partner = detail["partner"]["raw_label"].strip()
    flow = detail["method_query"]["flow"]  # 'export' or 'import'
    current_end = detail["windows"]["current_end"]

    # GACC's flow label is China-as-reporter:
    #   flow=export  →  China exports to <partner>   →  <partner> imports from China
    #   flow=import  →  China imports from <partner> →  <partner> exports to China
    if flow == "export":
        china_direction = f"China exports to {partner}"
        partner_direction = f"**{partner} imports from China**"
    else:
        china_direction = f"China imports from {partner}"
        partner_direction = f"**{partner} exports to China**"

    cur_eur = totals["current_12mo_eur"]
    yoy = totals["yoy_pct"]
    missing_cur = totals.get("missing_months_current") or []
    missing_prior = totals.get("missing_months_prior") or []

    parts: list[str] = []
    parts.append(f"# finding/{finding['id']} — provenance\n")
    parts.append(_generated_banner(finding["id"]) + "\n")
    parts.append(f"**{finding['title']}**\n")
    parts.append(
        f"From the partner side, this is {partner_direction}. The GACC label "
        f"reads as *{china_direction}* because China is the reporting "
        f"authority; same money, opposite directional reading.\n"
    )
    parts.append(_supersede_status(finding) + "\n")
    parts.append("")

    # ---- Sources -----------------------------------------------------------
    parts.append("## Sources\n")
    parts.append(
        "Single-source finding. Every monthly value is read from a GACC "
        "section-4 release (\"China's Total Export & Import Values by "
        "Country/Region\"), in the table row labelled with the partner name "
        "and the column matching the flow direction. Values on the page are "
        "in units of 100 million CNY (亿元).\n"
    )
    parts.append(_sources_table(finding) + "\n")
    parts.append("")

    if missing_cur or missing_prior:
        parts.append("### Missing months\n")
        if missing_cur:
            parts.append(
                f"Current 12mo window is missing: "
                f"{', '.join(str(m) for m in missing_cur)}.  \n"
            )
        if missing_prior:
            parts.append(
                f"Prior 12mo window is missing: "
                f"{', '.join(str(m) for m in missing_prior)}.  \n"
            )
        parts.append(
            "These are structural data gaps — GACC publishes January + "
            "February as a single combined release (Chinese New Year) and "
            "the parser doesn't yet handle that combined format. The YTD "
            "operator below is unaffected (read directly from the release's "
            "year-to-date cell, not re-summed from monthly cells).\n"
        )
        parts.append("")

    # ---- Caveats -----------------------------------------------------------
    parts.append("## Caveats (plain English)\n")
    parts.append(_caveat_glossary(detail.get("caveat_codes") or []) + "\n")
    parts.append(
        "Family-universal caveats (CIF/FOB, currency timing, classification "
        "drift, etc. — see the brief's Methodology footer or "
        "[docs/methodology.md §3](../docs/methodology.md#3-caveats-reference)) "
        "apply to every bilateral aggregate finding and are not repeated "
        "per-finding.\n"
    )
    parts.append("")

    # ---- Cross-source ------------------------------------------------------
    parts.append("## Cross-source corroboration\n")
    parts.append(_cross_source_block(finding) + "\n")

    # ---- Headline arithmetic ----------------------------------------------
    parts.append("## Headline arithmetic\n")
    n_cur_months = 12 - len(missing_cur)
    n_prior_months = 12 - len(missing_prior)
    parts.append(
        f"Sum of the {n_cur_months} monthly EUR values in the current "
        f"window (after converting each month's CNY value at the ECB "
        f"monthly-average CNY/EUR rate for that month):  \n"
        f"  **Current ({n_cur_months}/12 months to {current_end})**: "
        f"{_fmt_eur(cur_eur)}  \n"
        f"  **Prior ({n_prior_months}/12 months)**: "
        f"{_fmt_eur(totals['prior_12mo_eur'])}  \n"
        f"  **YoY**: {_fmt_pct(yoy)}\n"
    )
    if totals.get("ytd_cumulative"):
        ytd = totals["ytd_cumulative"]
        parts.append(
            f"YTD ({ytd['months_in_ytd']} months through {current_end}): "
            f"{_fmt_eur(ytd['current_eur'])} (prior YTD "
            f"{_fmt_eur(ytd['prior_eur'])} → {_fmt_pct(ytd['yoy_pct'])}). "
            f"YTD values are read directly from GACC's published cumulative "
            f"cell on each release; they don't depend on the rolling 12mo "
            f"window's missing months.\n"
        )
    if totals.get("single_month"):
        sm = totals["single_month"]
        parts.append(
            f"Latest month ({sm['current_period']}): "
            f"{_fmt_eur(sm['current_eur'])} (prior-year same month "
            f"{_fmt_eur(sm['prior_eur'])} → {_fmt_pct(sm['yoy_pct'])}).\n"
        )
    parts.append("")

    # ---- Methodology link --------------------------------------------------
    parts.append("## Methodology\n")
    parts.append(
        f"Analyser: `{detail['method']}` "
        f"(`anomalies.detect_gacc_bilateral_aggregate_yoy`). Reads monthly "
        f"GACC section-4 observations where partner = `{partner}`, flow = "
        f"`{flow}`, currency = CNY. Each monthly CNY value is converted to "
        f"EUR using the ECB monthly-average CNY/EUR reference rate for that "
        f"same month (stored in the `fx_rates` table, "
        f"`currency_from='CNY' currency_to='EUR'`). Rolling 12mo and prior "
        f"12mo windows are summed in EUR; YoY is the ratio.  \n"
        f"See [docs/methodology.md §1.4](../docs/methodology.md) for the "
        f"full description.\n"
    )
    parts.append("")

    # ---- FX appendix -------------------------------------------------------
    parts.append("## Appendix A — ECB CNY/EUR rates used\n")
    parts.append(
        "Fetched from "
        "https://data-api.ecb.europa.eu/service/data/EXR/M.CNY.EUR.SP00.A?format=jsondata "
        "(ECB Data Portal public API). The table stores `1 CNY = X EUR` "
        "for convenience; multiply each month's 100M-CNY page value by "
        "1e8 and then by X to get the per-month EUR contribution.\n\n"
    )
    parts.append(_fx_table(finding) + "\n")

    # ---- Replay (technical) -----------------------------------------------
    parts.append("## Appendix B — Replay queries (for fact-checkers)\n")
    parts.append(
        "```sql\n"
        f"-- The finding row\n"
        f"SELECT id, title, body, detail FROM findings WHERE id = {finding['id']};\n\n"
        f"-- Every source observation, joined to its GACC release URL\n"
        f"SELECT o.id, r.period, r.source_url, o.value_amount, r.unit\n"
        f"  FROM observations o JOIN releases r ON r.id = o.release_id\n"
        f" WHERE o.id = ANY(\n"
        f"   (SELECT observation_ids FROM findings WHERE id = {finding['id']})\n"
        f" ) ORDER BY r.period;\n\n"
        f"-- The ECB rates used\n"
        f"SELECT rate_date, rate, rate_source_url\n"
        f"  FROM fx_rates\n"
        f" WHERE currency_from = 'CNY' AND currency_to = 'EUR'\n"
        f" ORDER BY rate_date;\n"
        "```\n"
    )
    parts.append(
        "To regenerate this finding from scratch (will produce a new finding "
        "id and supersede the current one if values differ):\n"
        f"```sh\npython scrape.py --analyse gacc-bilateral-aggregate-yoy --flow "
        f"{1 if flow == 'export' else 2}\n```\n"
    )

    return "\n".join(parts) + "\n"


def _sources_table(finding: dict) -> str:
    """Per-month table: period | source URL | page value | EUR | obs_id."""
    detail = finding["detail"]
    monthly_series = detail.get("monthly_series", [])
    eur_by_period = {m["period"]: m["value_eur"] for m in monthly_series}

    with _conn() as conn, conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
        cur.execute(
            """
            SELECT o.id, r.period, r.source_url, r.title,
                   o.value_amount, o.period_kind, o.flow, o.version_seen
              FROM observations o JOIN releases r ON r.id = o.release_id
             WHERE o.id = ANY(%s)
               AND r.source = 'gacc' AND r.currency = 'CNY'
               AND o.period_kind = 'monthly'
             ORDER BY r.period, o.id
            """,
            (finding["observation_ids"],),
        )
        rows = cur.fetchall()

    lines = [
        "| Period | Source release | Page value (100M CNY) | Converted EUR | obs id |",
        "|---|---|---:|---:|---|",
    ]
    for r in rows:
        pd = r["period"].isoformat()
        cny = float(r["value_amount"])
        eur = eur_by_period.get(r["period"].isoformat()) or eur_by_period.get(r["period"])
        eur_cell = _fmt_eur(eur) if eur is not None else "—"
        lines.append(
            f"| {pd[:7]} | [{r['title'] or pd}]({r['source_url']}) | "
            f"{cny:,.1f} | {eur_cell} | `{r['id']}` |"
        )
    return "\n".join(lines)


def _fx_table(finding: dict) -> str:
    """All FX rates touching the current+prior 12mo windows."""
    detail = finding["detail"]
    start = detail["windows"]["prior_start"]
    end = detail["windows"]["current_end"]
    with _conn() as conn, conn.cursor() as cur:
        cur.execute(
            """
            SELECT rate_date, rate
              FROM fx_rates
             WHERE currency_from = 'CNY' AND currency_to = 'EUR'
               AND rate_date BETWEEN %s AND %s
             ORDER BY rate_date
            """,
            (start, end),
        )
        rows = cur.fetchall()
    lines = ["| Period | 1 CNY = … EUR | (equivalently CNY per EUR) |", "|---|---:|---:|"]
    for rate_date, rate in rows:
        rate_f = float(rate)
        lines.append(
            f"| {rate_date.isoformat()[:7]} | {rate_f:.6f} | {1/rate_f:.4f} |"
        )
    return "\n".join(lines)


_CAVEAT_GLOSSARY: dict[str, str] = {
    "partial_window": (
        "Some months in the 12-month rolling window are missing on the source "
        "side (typically GACC's combined Jan+Feb release, which this parser "
        "doesn't yet split). The YoY % is therefore approximate — quote "
        "`rose roughly N%` rather than implying decimal precision."
    ),
    "cn8_revision": (
        "The 12-month window spans an annual CN8 (8-digit HS code) revision "
        "boundary. Some product-level YoY comparisons may be apples-to-pears "
        "if a code was renamed or split between the two years. The headline "
        "aggregate is robust; sub-category drilldowns may not be."
    ),
    "low_base_effect": (
        "The prior-year baseline value was below the low-base threshold "
        "(default €50M / 12mo), so percentage moves can look dramatic from "
        "a tiny denominator. Use absolute EUR figures, not percentages."
    ),
    "low_baseline_n": (
        "Fewer than the minimum number of (scope × flow) permutations had "
        "T-6 history when the predictability badge was computed. No green/"
        "amber/red badge is rendered for this finding; the headline number "
        "is fine but trend-stability claims are not supported."
    ),
    "low_kg_coverage": (
        "Less than the methodology threshold of the EUR-weighted CN8 lines "
        "had a kg quantity reported, so any kg/tonnes commentary on this "
        "finding rests on a thin sample. EUR-side figures are unaffected."
    ),
    "llm_drafted": (
        "Editorial prose for this finding was scaffolded by an LLM. Every "
        "number in the prose has been verified against the typed facts; "
        "any unverifiable number is rejected pre-publish. See the brief's "
        "leads.md for the LLM output itself."
    ),
    "cross_source_sum": (
        "This finding sums across two sources (Eurostat + HMRC) with "
        "different threshold rules, suppression policies, and revision "
        "cycles. The aggregate is methodologically imperfect — usable for "
        "headline scale, not for tight quantitative claims."
    ),
}


def _caveat_glossary(codes: list[str]) -> str:
    if not codes:
        return "No per-finding caveats."
    lines = []
    for code in codes:
        explanation = _CAVEAT_GLOSSARY.get(
            code,
            "(no plain-English entry yet — see the `caveats` table for the "
            "editorial guidance row.)",
        )
        lines.append(f"- **`{code}`** — {explanation}")
    return "\n".join(lines)


def _cross_source_block(finding: dict) -> str:
    """For a GACC bilateral finding, look up the Eurostat sum for the same
    partner over the same window and report agreement."""
    detail = finding["detail"]
    partner_raw = detail["partner"]["raw_label"].strip()
    flow = detail["method_query"]["flow"]
    start = detail["windows"]["current_start"]
    end = detail["windows"]["current_end"]

    # GACC's raw_label often contains the partner country with various
    # leading whitespace / "of which:" prefix. Strip to a plain country name.
    partner = partner_raw.replace("of which:", "").strip()

    # Map partner name → Eurostat reporter ISO2. We could route this through
    # the country_aliases table, but the half-dozen majors are enough for
    # this first cut.
    iso2 = {
        "Germany": "DE", "France": "FR", "Italy": "IT", "Netherlands": "NL",
        "Belgium": "BE", "Spain": "ES", "Poland": "PL", "Austria": "AT",
        "Sweden": "SE", "Hungary": "HU", "Czech Republic": "CZ",
        "United Kingdom": "GB",
    }.get(partner)
    if iso2 is None:
        return (
            f"No automatic Eurostat counterpart lookup for partner "
            f"`{partner}` yet — see `forward-work-uk-data-gap.md` and "
            f"`country_aliases` for the routing table."
        )

    # In GACC, flow=export means China exporting → partner imports.
    # In Eurostat, the partner is the reporter and flow=1 is imports.
    eurostat_flow = 1 if flow == "export" else 2

    with _conn() as conn, conn.cursor() as cur:
        cur.execute(
            """
            SELECT MIN(period), MAX(period), COUNT(DISTINCT period),
                   SUM(value_eur)
              FROM eurostat_raw_rows
             WHERE reporter = %s
               AND partner IN ('CN', 'HK', 'MO')
               AND flow = %s
               AND product_nc = '000TOTAL'
               AND stat_procedure = '1'
               AND period BETWEEN %s AND %s
            """,
            (iso2, eurostat_flow, start, end),
        )
        pmin, pmax, nperiods, sum_eur = cur.fetchone()

    if sum_eur is None:
        return (
            f"Eurostat counterpart for {iso2} over this window is not yet "
            f"ingested. Re-run `python scrape.py --eurostat-period YYYY-MM` "
            f"for the missing months if a cross-check is needed."
        )

    gacc_eur = detail["totals"]["current_12mo_eur"]
    eurostat_eur = float(sum_eur)
    # Eurostat may have fewer or more months than GACC for the same window
    # (publication lags differ). Normalise both to a per-month average for a
    # like-for-like comparison.
    gacc_months = 12 - len(detail["totals"].get("missing_months_current") or [])
    eurostat_avg_month = eurostat_eur / nperiods if nperiods else 0
    gacc_avg_month = gacc_eur / gacc_months if gacc_months else 0
    pct_gap = (eurostat_avg_month - gacc_avg_month) / gacc_avg_month if gacc_avg_month else 0

    direction = "imports from China" if flow == "export" else "exports to China"
    gap_word = "higher" if pct_gap > 0 else "lower"
    return (
        f"Eurostat publishes the same flow ({partner} {direction}) from the "
        f"partner-side, reporting under the COMEXT statistical product with "
        f"reporter=`{iso2}` and partner=`CN+HK+MO`. Over the {nperiods}-month "
        f"overlap ({pmin} → {pmax}, stat_procedure=1, product_nc='000TOTAL'):\n\n"
        f"- GACC (this finding, {gacc_months} months): {_fmt_eur(gacc_eur)} "
        f"(~{_fmt_eur(gacc_avg_month)}/month average)\n"
        f"- Eurostat ({nperiods} months): {_fmt_eur(eurostat_eur)} "
        f"(~{_fmt_eur(eurostat_avg_month)}/month average)\n"
        f"- Per-month gap: Eurostat is {abs(pct_gap)*100:.1f}% {gap_word} "
        f"than GACC.\n\n"
        f"A single-digit-percent gap between the two sources is expected and "
        f"not a quality concern — the two are measuring methodologically "
        f"different things. Eurostat values imports CIF (cost+insurance+"
        f"freight at the EU port of entry, typically ~5-10% above the goods "
        f"value alone); GACC values exports FOB (free-on-board at the "
        f"Chinese port of departure). Working in the opposite direction, "
        f"transshipment routing (some Chinese-origin goods arrive in Europe "
        f"via Hong Kong or Singapore and don't always count identically on "
        f"both sides) can push Eurostat below GACC. The net direction "
        f"varies by partner and period."
    )


def _render_stub(finding: dict) -> str:
    """Fallback for subkinds we haven't built a detailed renderer for yet."""
    return (
        f"# finding/{finding['id']} — provenance\n\n"
        + _generated_banner(finding["id"])
        + f"\n**{finding['title']}**\n\n"
        + f"- Kind: `{finding['kind']}`  \n"
        + f"- Subkind: `{finding['subkind']}`  \n"
        + _supersede_status(finding) + "\n\n"
        + f"## Detailed provenance generator pending\n\n"
        + f"The auto-generated provenance template for subkind "
        + f"`{finding['subkind']}` is not yet implemented. The finding row "
        + f"is verifiable directly:\n\n"
        + "```sql\n"
        + f"SELECT id, title, body, detail FROM findings WHERE id = "
        + f"{finding['id']};\n"
        + "```\n\n"
        + "For a bespoke provenance audit on this finding, contact the "
        + "project maintainer — and consider extending "
        + f"`provenance._RENDERERS` to cover `{finding['subkind']}`.\n"
    )


def _render_hs_group_yoy(finding: dict) -> str:
    """HS group year-on-year (Eurostat / HMRC / combined). Handles all six
    subkinds — flow ∈ {import, export} × scope ∈ {eu_27, uk, eu_27_plus_uk} —
    in one renderer; they share the same detail shape and only differ in
    which source(s) the rows came from."""
    detail = finding["detail"]
    totals = detail["totals"]
    method_q = detail["method_query"]
    group = detail["group"]
    flow = method_q["flow"]  # 1 or 2
    scope = method_q["comparison_scope"]
    sources = method_q.get("sources", [])
    partners = method_q.get("partners", [])

    flow_word = "imports from" if flow == 1 else "exports to"
    scope_word = {
        "eu_27": "EU-27 (Eurostat)",
        "uk": "UK (HMRC)",
        "eu_27_plus_uk": "EU-27 + UK combined (Eurostat + HMRC)",
    }.get(scope, scope)
    direction_human = f"{scope_word} {flow_word} China"

    cur_end = totals.get("missing_months_current") and "(partial)" or ""

    parts: list[str] = []
    parts.append(f"# finding/{finding['id']} — provenance\n")
    parts.append(_generated_banner(finding["id"]) + "\n")
    parts.append(f"**{finding['title']}**\n")
    parts.append(
        f"This is **{direction_human}**, summed across partners "
        f"{', '.join(partners) or '(none specified)'} (mainland China plus "
        f"the Hong Kong and Macau SARs, which Eurostat reports separately "
        f"but China editorially counts as the same trade envelope).\n"
    )
    parts.append(_supersede_status(finding) + "\n")
    parts.append("")

    # ---- What's in this HS group ------------------------------------------
    # Luke's pack-review note (2026-05-13-1547_pack-review.txt) flagged that
    # journalists need an explicit definition of what each group covers.
    parts.append("## What's in this HS group\n")
    parts.append(f"**{group['name']}**  \n")
    desc = (group.get("description") or "").strip()
    if desc:
        parts.append(f"{desc}\n")
    pats = group.get("hs_patterns") or method_q.get("hs_patterns") or []
    parts.append(
        f"HS pattern(s) matched: "
        f"{', '.join(f'`{p}`' for p in pats) or '(none)'}. Each pattern is "
        f"used as a SQL `LIKE` against the raw row's CN8 code (`product_nc` "
        f"on Eurostat, `cn8_code` on HMRC). Codes that don't match any "
        f"pattern aren't in this group's total.\n"
    )
    parts.append("")

    # ---- Sources -----------------------------------------------------------
    parts.append("## Sources\n")
    parts.append(_hs_group_sources_block(detail, sources))
    parts.append("")

    # ---- Caveats -----------------------------------------------------------
    parts.append("## Caveats (plain English)\n")
    parts.append(_caveat_glossary(detail.get("caveat_codes") or []) + "\n")
    parts.append(
        "Family-universal caveats — `cif_fob` (Eurostat imports valued "
        "CIF, ~5-10% above the goods value alone), `currency_timing` (FX "
        "applied at the month-of-trade rate, not the contract rate), "
        "`classification_drift` (CN8 codes evolve over the years; some "
        "drift is unavoidable), `eurostat_stat_procedure_mix`, "
        "`multi_partner_sum` (CN+HK+MO summed), `cn8_revision` — apply to "
        "every hs_group_yoy finding and live in the brief's Methodology "
        "footer rather than per finding.\n"
    )
    parts.append("")

    # ---- Headline arithmetic ----------------------------------------------
    parts.append("## Headline arithmetic\n")
    n_cur = totals.get("n_months_used_current", 12 - len(totals.get("missing_months_current") or []))
    n_pri = totals.get("n_months_used_prior", 12 - len(totals.get("missing_months_prior") or []))
    parts.append(
        f"Sum across all matching raw rows (Eurostat / HMRC, summed per "
        f"month then summed over the window):  \n"
        f"  **Current ({n_cur}/12 months to {detail['windows']['current_end']})**: "
        f"{_fmt_eur(totals['current_12mo_eur'])}, "
        f"{_fmt_kg(totals.get('current_12mo_kg'))}.  \n"
        f"  **Prior ({n_pri}/12 months)**: "
        f"{_fmt_eur(totals['prior_12mo_eur'])}, "
        f"{_fmt_kg(totals.get('prior_12mo_kg'))}.  \n"
        f"  **YoY (value)**: {_fmt_pct(totals['yoy_pct'])}  \n"
        f"  **YoY (kg)**: {_fmt_pct(totals.get('yoy_pct_kg') or 0)}  \n"
        f"  **Unit price change**: {_fmt_pct(totals.get('unit_price_pct_change') or 0)} "
        f"(€/kg from "
        f"{(totals.get('prior_unit_price_eur_per_kg') or 0):.2f} → "
        f"{(totals.get('current_unit_price_eur_per_kg') or 0):.2f})\n"
    )
    if totals.get("single_month"):
        sm = totals["single_month"]
        parts.append(
            f"Latest single month ({sm['current_period']}): "
            f"{_fmt_eur(sm['current_eur'])} vs "
            f"{_fmt_eur(sm['prior_eur'])} a year earlier "
            f"→ {_fmt_pct(sm['yoy_pct'])} (kg {_fmt_pct(sm.get('yoy_pct_kg') or 0)}).\n"
        )
    if totals.get("two_month_cumulative"):
        tm = totals["two_month_cumulative"]
        parts.append(
            f"Latest two-month cumulative: {_fmt_eur(tm['current_eur'])} vs "
            f"{_fmt_eur(tm['prior_eur'])} a year earlier "
            f"→ {_fmt_pct(tm['yoy_pct'])}.\n"
        )
    if totals.get("kg_coverage_pct") is not None:
        cov = totals["kg_coverage_pct"]
        thresh = totals.get("kg_coverage_threshold", 0.8)
        cov_note = "above the 80% reliability threshold" if cov >= thresh else (
            "below the 80% reliability threshold — unit-price moves on this "
            "finding should be treated as indicative, not quantitative"
        )
        parts.append(
            f"Kilogram coverage: {cov*100:.0f}% of EUR-weighted rows in the "
            f"current 12mo window carry a quantity_kg value ({cov_note}).\n"
        )
    parts.append("")

    # ---- Top reporter contributions ---------------------------------------
    pr_breakdown = detail.get("per_reporter_breakdown") or []
    if pr_breakdown:
        parts.append("## Top reporter contributions to the YoY change\n")
        parts.append(
            "Per-reporter slice of the 12-month YoY delta. \"Share of "
            "group's delta\" is each country's contribution to the "
            "group-wide value change — useful for spotting when a single "
            "member state drives the move (e.g. \"Germany alone explains "
            "60%\"). Negative shares mean the country moved *opposite* to "
            "the group total.\n"
        )
        lines = [
            "| Reporter | Current 12mo | Prior 12mo | YoY | Share of group's delta |",
            "|---|---:|---:|---:|---:|",
        ]
        for r in pr_breakdown[:10]:
            lines.append(
                f"| {r.get('reporter', '?')} "
                f"| {_fmt_eur(r.get('current_eur') or 0)} "
                f"| {_fmt_eur(r.get('prior_eur') or 0)} "
                f"| {_fmt_pct(r.get('yoy_pct') or 0)} "
                f"| {(r.get('share_of_group_delta_pct') or 0)*100:+.0f}% |"
            )
        parts.append("\n".join(lines) + "\n")
        parts.append("")

    # ---- Top CN8 contributions --------------------------------------------
    top_cn8 = detail.get("top_cn8_codes_in_current_12mo") or []
    if top_cn8:
        parts.append("## Top CN8 codes contributing in the current 12mo window\n")
        parts.append(
            "Within the HS pattern(s) above, these CN8 codes (8-digit "
            "Harmonised System) carried the most EUR value in the current "
            "12 months. Useful for sanity-checking whether the group's "
            "headline number is dominated by a single CN8 (which would "
            "make a future code rename / split a material risk).\n"
        )
        lines = [
            "| CN8 code | Current 12mo | Quantity | Unit price |",
            "|---|---:|---:|---:|",
        ]
        for r in top_cn8[:10]:
            kg = r.get("total_kg") or 0
            eur = r.get("total_eur") or 0
            unit = (eur / kg) if kg else None
            lines.append(
                f"| `{r.get('product_nc') or r.get('cn8') or '?'}` "
                f"| {_fmt_eur(eur)} "
                f"| {_fmt_kg(kg)} "
                f"| {f'€{unit:.2f}/kg' if unit else '—'} |"
            )
        parts.append("\n".join(lines) + "\n")
        parts.append("")

    # ---- Methodology ------------------------------------------------------
    parts.append("## Methodology\n")
    parts.append(
        f"Analyser: `{detail['method']}` "
        f"(`anomalies.detect_hs_group_yoy`). For each calendar month in "
        f"the rolling-12 window, sums `value_eur` and `quantity_kg` across "
        f"all raw rows where: (a) `flow = {flow}` (1=import, 2=export), "
        f"(b) the partner is in `{partners}`, (c) the CN8 code matches at "
        f"least one HS pattern above. "
        f"Source = "
        f"{('Eurostat (`eurostat_raw_rows`)' if 'eurostat' in sources else '')}"
        f"{(' + ' if len(sources) == 2 else '')}"
        f"{('HMRC OTS (`hmrc_raw_rows`)' if 'hmrc' in sources else '')}. "
        f"YoY is `(current_sum - prior_sum) / prior_sum`. The kg and "
        f"unit-price decomposition is informational; the headline EUR "
        f"figure is canonical.  \n"
        f"See [docs/methodology.md §1.1](../docs/methodology.md) for the "
        f"full description, including unit-price reliability gating and "
        f"the per-reporter breakdown rules.\n"
    )
    parts.append("")

    # ---- Replay -----------------------------------------------------------
    parts.append("## Appendix — Replay queries (for fact-checkers)\n")
    flow_cli = 1 if flow == 1 else 2
    scope_cli = scope
    parts.append(
        "```sql\n"
        f"-- The finding row\n"
        f"SELECT id, title, body, detail FROM findings WHERE id = {finding['id']};\n\n"
        f"-- Reproduce the current 12mo total from raw rows "
        f"(Eurostat side, single source for this finding's scope):\n"
        + _replay_sql(detail, sources)
        + "```\n"
    )
    parts.append(
        "To regenerate this finding from scratch (will produce a new "
        "finding id and supersede the current one if values differ):\n"
        f"```sh\npython scrape.py --analyse hs-group-yoy --flow {flow_cli} "
        f"--comparison-scope {scope_cli} "
        f"--hs-group {group['name']!r}\n```\n"
    )

    return "\n".join(parts) + "\n"


def _hs_group_sources_block(detail: dict, sources: list[str]) -> str:
    """List the underlying release URLs for the periods touching the 12mo
    window. For Eurostat: one bulk file per month (each contains all
    reporters × all partners × all CN8). For HMRC: one OData query per
    month. The same release URL covers every HS group; this finding picks
    rows out of it by flow/partner/CN8 filter — those filters are in the
    methodology section."""
    start = detail["windows"]["prior_start"]
    end = detail["windows"]["current_end"]
    with _conn() as conn, conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
        cur.execute(
            """
            SELECT source, period, source_url
              FROM releases
             WHERE source = ANY(%s)
               AND period BETWEEN %s AND %s
             ORDER BY source, period
            """,
            (sources, start, end),
        )
        rows = cur.fetchall()
    by_source: dict[str, list[dict]] = {}
    for r in rows:
        by_source.setdefault(r["source"], []).append(r)

    out = []
    for src in sources:
        rs = by_source.get(src, [])
        if not rs:
            out.append(
                f"### {src.upper()}\n\n"
                f"No releases ingested in the window {start} → {end}. "
                f"The finding's totals would be zero for that source.\n"
            )
            continue
        label = {
            "eurostat": (
                "**Eurostat COMEXT** — monthly bulk file containing every "
                "(EU reporter × world partner × CN8) cell. Each release URL "
                "below is the canonical 7-zip download for that month; "
                "filters (flow, partner, CN8 pattern) are applied on read."
            ),
            "hmrc": (
                "**HMRC OTS** — Overseas Trade Statistics via the "
                "uktradeinfo.com OData REST API. Each URL is the exact "
                "OData query our scraper used at ingest time; partner "
                "filter (CN/HK/MO) is encoded in the URL."
            ),
        }.get(src, src.upper())
        out.append(f"### {src.upper()}\n\n{label}\n\n")
        out.append("| Period | Source release |")
        out.append("|---|---|")
        for r in rs:
            url = r["source_url"]
            label_text = _short_url_label(src, url)
            out.append(f"| {r['period'].isoformat()[:7]} | [{label_text}]({url}) |")
        out.append("")
    return "\n".join(out)


def _short_url_label(source: str, url: str) -> str:
    """Friendly link text for a release URL. Keeps the table compact; the
    full URL is still the href.
    - Eurostat bulk files → the filename, e.g. `full_v2_202506.7z`.
    - HMRC OData queries → `OTS query (MonthId=YYYYMM)` if MonthId can be parsed.
    - Fallback → middle-truncated URL."""
    if source == "eurostat":
        import urllib.parse
        downfile = urllib.parse.parse_qs(urllib.parse.urlparse(url).query).get("downfile", [""])[0]
        return downfile.rsplit("/", 1)[-1] or url
    if source == "hmrc":
        import re
        m = re.search(r"MonthId eq (\d{6})", url)
        return f"HMRC OTS OData query (MonthId={m.group(1)})" if m else "HMRC OTS OData query"
    return url if len(url) <= 80 else url[:38] + "…" + url[-38:]


def _replay_sql(detail: dict, sources: list[str]) -> str:
    """Generate a copy-pasteable SQL block that re-sums the current 12mo
    total from raw rows. Per source — the journalist can run either / both
    to verify the headline EUR figure."""
    method_q = detail["method_query"]
    flow = method_q["flow"]
    partners = method_q.get("partners", [])
    patterns = (detail.get("group") or {}).get("hs_patterns") or method_q.get("hs_patterns") or []
    start = detail["windows"]["current_start"]
    end = detail["windows"]["current_end"]
    like_or = " OR ".join(f"product_nc LIKE '{p}'" for p in patterns) or "TRUE"
    blocks = []
    if "eurostat" in sources:
        blocks.append(
            f"-- Eurostat side:\n"
            f"SELECT period, SUM(value_eur) AS eur, SUM(quantity_kg) AS kg\n"
            f"  FROM eurostat_raw_rows\n"
            f" WHERE flow = {flow}\n"
            f"   AND partner = ANY('{{{','.join(partners)}}}')\n"
            f"   AND ({like_or})\n"
            f"   AND period BETWEEN '{start}' AND '{end}'\n"
            f"   AND reporter NOT IN ('GB', 'XI', 'XU')   -- EU-27 excludes UK\n"
            f" GROUP BY period ORDER BY period;\n\n"
        )
    if "hmrc" in sources:
        # HMRC stores cn8 as cn8_code; build LIKE on that.
        like_or_hmrc = " OR ".join(f"cn8_code LIKE '{p}'" for p in patterns) or "TRUE"
        blocks.append(
            f"-- HMRC side:\n"
            f"SELECT period, SUM(value_eur) AS eur, SUM(net_mass_kg) AS kg\n"
            f"  FROM hmrc_raw_rows\n"
            f" WHERE flow = {flow}\n"
            f"   AND partner = ANY('{{{','.join(partners)}}}')\n"
            f"   AND ({like_or_hmrc})\n"
            f"   AND period BETWEEN '{start}' AND '{end}'\n"
            f"   AND suppression_index = 0\n"
            f" GROUP BY period ORDER BY period;\n\n"
        )
    return "".join(blocks)


def _fmt_kg(v: float | None) -> str:
    if v is None or v == 0:
        return "—"
    if abs(v) >= 1e9:
        return f"{v/1e9:.2f} bn kg"
    if abs(v) >= 1e6:
        return f"{v/1e6:.1f}M kg"
    if abs(v) >= 1e3:
        return f"{v/1e3:.0f}k kg"
    return f"{v:,.0f} kg"


_RENDERERS = {
    "gacc_bilateral_aggregate_yoy": _render_gacc_bilateral_aggregate_yoy,
    "gacc_bilateral_aggregate_yoy_import": _render_gacc_bilateral_aggregate_yoy,
    "hs_group_yoy": _render_hs_group_yoy,
    "hs_group_yoy_export": _render_hs_group_yoy,
    "hs_group_yoy_uk": _render_hs_group_yoy,
    "hs_group_yoy_uk_export": _render_hs_group_yoy,
    "hs_group_yoy_combined": _render_hs_group_yoy,
    "hs_group_yoy_combined_export": _render_hs_group_yoy,
}
